apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.posix.name }}
  labels:
    app: {{ .Values.posix.app }}
spec:
  hostname: {{ .Values.posix.hostname }}
  nodeSelector:
    nodename: {{ .Values.posix.nodeSelector }}
  containers:
    - name: {{ .Values.posix.containerName }}
      image: {{ .Values.posix.image }}
      env:
        - name: hostname
          value: {{ .Values.posix.env.hostname | quote }}
        - name: ports
          value: {{ .Values.posix.env.ports | quote }}
        - name: entrypoint
          value: {{ .Values.posix.env.entrypoint | quote }}
        - name: XrdSecGSISRVNAMES
          value: {{ .Values.posix.env.XrdSecGSISRVNAMES | quote }}
      ports:
        - containerPort: {{ .Values.posix.containerPort }}
      volumeMounts:
        - name: grid-security-volume
          mountPath: /etc/grid-security
          readOnly: true
        - name: vomses-volume
          mountPath: /etc/vomses
          readOnly: true
        - name: local-bin-volume
          mountPath: /usr/local/bin
          readOnly: true
        - name: xrootd-config-volume
          mountPath: /etc/xrootd
          readOnly: true
        - name: data-volume
          mountPath: /data
          readOnly: false
        - name: entrypoint-volume
          mountPath: /entrypoint
          readOnly: true
      command: ["/entrypoint/entrypoint1.sh"]
  volumes:
    - name: grid-security-volume
      nfs:
        server: {{ .Values.nfs.server }}
        path: {{ .Values.nfs.paths.gridSecurity }}
    - name: vomses-volume
      nfs:
        server: {{ .Values.nfs.server }}
        path: {{ .Values.nfs.paths.vomses }}
    - name: local-bin-volume
      nfs:
        server: {{ .Values.nfs.server }}
        path: {{ .Values.nfs.paths.localBin }}
    - name: xrootd-config-volume
      nfs:
        server: {{ .Values.nfs.server }}
        path: {{ .Values.nfs.paths.xrootdConfig }}
    - name: data-volume
      nfs:
        server: {{ .Values.nfs.server }}
        path: {{ .Values.nfs.paths.data }}
    - name: entrypoint-volume
      nfs:
        server: {{ .Values.nfs.server }}
        path: {{ .Values.nfs.paths.entrypoint }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.posix.service.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.posix.app }}
  ports:
    - name: {{ .Values.posix.service.portName }}
      protocol: TCP
      port: {{ .Values.posix.service.port }}
      targetPort: {{ .Values.posix.service.targetPort }}
      nodePort: {{ .Values.posix.service.nodePort }}
